### PR TITLE
feature/UP-203

### PR DESCRIPTION
**Pull request by thinkberg**
UP-203 #close fix test bugs

### CODE REVIEW

**Comment by cvandrei** [comment]
Tests in `PublicKeyManagerSpec` look good now and thanks for fixing the one broken test in `PublicKeyUtilSpec`...I hadn't noticed that one yet.

Running the tests on my machine there's two broken ones in `KeyServiceClientRestSpec`:

```
feature("pubKeyDELETE()") {

    scenario("key does not exist; valid signature --> true") {}

    scenario("key exists; invalid signature --> true and delete key") {}

}
```

Can you reproduce these?

**Comment by thinkberg** [comment]
Fixed. Pretty lazy tests, they were duplicated badly and its only possible to run if the key server runs. The tests should use a mocked server layer.

**Comment by cvandrei** [comment]
Thanks for fixing the REST client tests, too.

I find the point you're making about "Pretty lazy tests" very much valid and in my opinion it touches on the topic of writing maintainable tests. Reducing duplication in tests can make them harder to maintain (been there, done that) and not knowing how the code will develop I chose to have tests more independent of each other (plus copy&pasting saved time, too). They are very short tests, too. If it turns out the code behind it is rather stable I'd see the sense of refactored them to reduce duplication.

As for mocking the server...I very much disagree. Then we might as well just delete the test as it's sole purpose would be to test how the mock behaves. The idea here is to test the integration of REST endpoints, the server and database. This already helped me save development time by sometimes finding bugs in the endpoints and/or server. Bugs I wouldn't have found without a full server integration.
The argument of wanting to mock the server to me feels like arguing that the database should be mocked in `KeyManagerSpec` where the intention is to cover the manager code and the database.
What I'm trying to say here: this touches a lot on test philosophies so your opinion is of course as valid as mine. My opinion is informed by 10 years of experience and believe me that I've written my share of unmaintainable tests many years ago. If you'd like to continue the discussion of what, how, why, etc we test then I'm more than open to it.
There's also a book about Test patterns that I can very much recommend: http://xunitpatterns.com/

**Comment by thinkberg** [comment]
There should be a test that the correct request (URL) and the correct payload is generated for the API layer. An integration test should test the actual REST endpoint by firing up a single endpoint and testing it.

**Comment by thinkberg** [comment]
please merge when everything looks okay

**Comment by cvandrei** [comment]
thx

**Pull request merged**
